name: Download and Upload Videos

on:
  schedule:
    # Run at 12 AM UTC every day
    - cron: '0 0 * * *'
  workflow_dispatch:  # Allow manual trigger for testing

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Setup YouTube credentials
        env:
          YOUTUBE_CLIENT_SECRETS: ${{ secrets.YOUTUBE_CLIENT_SECRETS }}
          YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}
        run: |
          echo "$YOUTUBE_CLIENT_SECRETS" > client_secrets.json
          echo "$YOUTUBE_TOKEN" > youtube_token.json

      - name: Run download and upload script
        run: python .github/scripts/download_and_upload.py
        env:
          YOUTUBE_TOKEN: ${{ secrets.YOUTUBE_TOKEN }}